# Generated by Django 3.0.7 on 2020-06-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('device', models.CharField(max_length=64)),
                ('stress', models.CharField(max_length=256)),
                ('page', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=64)),
                ('delay', models.IntegerField()),
            ],
        ),
    ]
