# Generated by Django 3.0.7 on 2020-06-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_testing_log_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrecord',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
