# Generated by Django 3.0.7 on 2020-07-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_testing_log_server', '0002_auto_20200629_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logrecord',
            name='stress',
        ),
        migrations.AddField(
            model_name='logrecord',
            name='cpu_stress',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='logrecord',
            name='disk_stress',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='logrecord',
            name='memory_stress',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='logrecord',
            name='network_stress',
            field=models.IntegerField(default=-1),
        ),
    ]
